version: "3.9"

services:
  postgesql:
    image: postgres:15-bullseye
    container_name: api_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
