version: "3.9"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

networks:
  web_api:
    driver: bridge