version: "3.9"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - postgresql
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  postgresql:
    image: postgres:15-bullseye
    container_name: api_postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=btc_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api

networks:
  web_api:
    driver: bridge