server:
  AppVersion: 1.0.0
  Port: :8080
  Env: Development
  ReadTimeout: 10
  WriteTimeout: 10

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: postgresql
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: btc_db
  PostgresqlSslmode: false
  PgDriver: pgx