server:
  AppVersion: 1.0.0
  Port: :8080
  Env: Development
  ReadTimeout: 5
  WriteTimeout: 5

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info