basePath: /api/v1
definitions:
  models.Transaction:
    properties:
      amount:
        type: number
      datetime:
        type: string
      id:
        type: string
    required:
    - amount
    - datetime
    type: object
info:
  contact:
    email: andre.katsuragawa@gmail.com
    name: Andre Katsuragawa
    url: https://github.com/katsuragawaa
  description: App that allows users to track the balance of a bitcoin wallet over
    time
  title: BTC Billionaire
  version: "1.0"
paths:
  /comments:
    post:
      consumes:
      - application/json
      description: Create new bitcoin transaction
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
      summary: Create new transaction
      tags:
      - Transaction
  /ping:
    get:
      consumes:
      - application/json
      description: Ping server for health check
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Ping app
      tags:
      - Health
swagger: "2.0"
