basePath: /api/v1
definitions:
  models.Transaction:
    properties:
      amount:
        type: number
      created_at:
        type: string
      datetime:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - amount
    - datetime
    type: object
  models.TransactionBase:
    properties:
      amount:
        type: number
      datetime:
        type: string
    type: object
  models.TransactionsBalance:
    properties:
      total_amount:
        type: number
    type: object
  models.TransactionsList:
    properties:
      transactions:
        items:
          $ref: '#/definitions/models.TransactionBase'
        type: array
    type: object
info:
  contact:
    email: andre.katsuragawa@gmail.com
    name: Andre Katsuragawa
    url: https://github.com/katsuragawaa
  description: App that allows users to track the balance of a bitcoin wallet over
    time
  title: BTC Billionaire
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping server for health check
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Ping app
      tags:
      - Health
  /transactions:
    get:
      consumes:
      - application/json
      description: Get bitcoin transactions within a time interval
      parameters:
      - description: interval start datetime
        in: query
        name: startDatetime
        required: true
        type: string
      - description: interval end datetime
        in: query
        name: endDatetime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionsList'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get transactions within a time interval
      tags:
      - Transaction
    post:
      consumes:
      - application/json
      description: Create new bitcoin transaction
      parameters:
      - description: Send new transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.TransactionBase'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create new transaction
      tags:
      - Transaction
  /transactions/balance:
    get:
      consumes:
      - application/json
      description: Get total bitcoin balance in the wallet
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionsBalance'
        "500":
          description: Internal Server Error
      summary: Get wallet total balance
      tags:
      - Transaction
swagger: "2.0"
